// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinDecision int32

const (
	JoinDecision_JOIN_DECISION_UNDECIDED JoinDecision = 0
	JoinDecision_JOIN_DECISION_COMMIT    JoinDecision = 1
	JoinDecision_JOIN_DECISION_ABORT     JoinDecision = 2
)

// Enum value maps for JoinDecision.
var (
	JoinDecision_name = map[int32]string{
		0: "JOIN_DECISION_UNDECIDED",
		1: "JOIN_DECISION_COMMIT",
		2: "JOIN_DECISION_ABORT",
	}
	JoinDecision_value = map[string]int32{
		"JOIN_DECISION_UNDECIDED": 0,
		"JOIN_DECISION_COMMIT":    1,
		"JOIN_DECISION_ABORT":     2,
	}
)

func (x JoinDecision) Enum() *JoinDecision {
	p := new(JoinDecision)
	*p = x
	return p
}

func (x JoinDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_proto_enumTypes[0].Descriptor()
}

func (JoinDecision) Type() protoreflect.EnumType {
	return &file_proto_kv_proto_enumTypes[0]
}

func (x JoinDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinDecision.Descriptor instead.
func (JoinDecision) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Versions      []*VersionedRecord     `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	Context       map[string]uint64      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Conflict      bool                   `protobuf:"varint,5,opt,name=conflict,proto3" json:"conflict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetVersions() []*VersionedRecord {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *GetResponse) GetContext() map[string]uint64 {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetResponse) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

// A value or deletion together with its causal version.
type VersionedRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Clock         map[string]uint64      `protobuf:"bytes,2,rep,name=clock,proto3" json:"clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedRecord) Reset() {
	*x = VersionedRecord{}
	mi := &file_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedRecord) ProtoMessage() {}

func (x *VersionedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedRecord.ProtoReflect.Descriptor instead.
func (*VersionedRecord) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *VersionedRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VersionedRecord) GetClock() map[string]uint64 {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *VersionedRecord) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Requests that a replica apply a complete versioned record.
type ReplicaRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Record        *VersionedRecord       `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaRecordRequest) Reset() {
	*x = ReplicaRecordRequest{}
	mi := &file_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRecordRequest) ProtoMessage() {}

func (x *ReplicaRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRecordRequest.ProtoReflect.Descriptor instead.
func (*ReplicaRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicaRecordRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ReplicaRecordRequest) GetRecord() *VersionedRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// Acknowledges successful processing.
// An outdated or identical record may be ignored by the store.
type ReplicaRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaRecordResponse) Reset() {
	*x = ReplicaRecordResponse{}
	mi := &file_proto_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRecordResponse) ProtoMessage() {}

func (x *ReplicaRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRecordResponse.ProtoReflect.Descriptor instead.
func (*ReplicaRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{8}
}

type ReplicaRecordReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Compatibility field for existing single-record readers.
	Record *VersionedRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Exists bool             `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	// Complete version list for sibling-aware readers.
	Records       []*VersionedRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaRecordReadResponse) Reset() {
	*x = ReplicaRecordReadResponse{}
	mi := &file_proto_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRecordReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRecordReadResponse) ProtoMessage() {}

func (x *ReplicaRecordReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRecordReadResponse.ProtoReflect.Descriptor instead.
func (*ReplicaRecordReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicaRecordReadResponse) GetRecord() *VersionedRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ReplicaRecordReadResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ReplicaRecordReadResponse) GetRecords() []*VersionedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Context       map[string]uint64      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_proto_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ResolveRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResolveRequest) GetContext() map[string]uint64 {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResolveRequest) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_proto_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{11}
}

// Requests a Merkle summary for data shared by requester and responder.
type AntiEntropySummaryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequesterNodeId     string                 `protobuf:"bytes,1,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	ReplicationFactor   int32                  `protobuf:"varint,2,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	ConfigurationDigest []byte                 `protobuf:"bytes,3,opt,name=configuration_digest,json=configurationDigest,proto3" json:"configuration_digest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AntiEntropySummaryRequest) Reset() {
	*x = AntiEntropySummaryRequest{}
	mi := &file_proto_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropySummaryRequest) ProtoMessage() {}

func (x *AntiEntropySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropySummaryRequest.ProtoReflect.Descriptor instead.
func (*AntiEntropySummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{12}
}

func (x *AntiEntropySummaryRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

func (x *AntiEntropySummaryRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *AntiEntropySummaryRequest) GetConfigurationDigest() []byte {
	if x != nil {
		return x.ConfigurationDigest
	}
	return nil
}

type AntiEntropySummaryResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResponderNodeId     string                 `protobuf:"bytes,1,opt,name=responder_node_id,json=responderNodeId,proto3" json:"responder_node_id,omitempty"`
	ConfigurationDigest []byte                 `protobuf:"bytes,2,opt,name=configuration_digest,json=configurationDigest,proto3" json:"configuration_digest,omitempty"`
	RootDigest          []byte                 `protobuf:"bytes,3,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	// Index in this array is the anti-entropy bucket number.
	// Every entry must be a SHA-256 digest.
	BucketDigests [][]byte `protobuf:"bytes,4,rep,name=bucket_digests,json=bucketDigests,proto3" json:"bucket_digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiEntropySummaryResponse) Reset() {
	*x = AntiEntropySummaryResponse{}
	mi := &file_proto_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropySummaryResponse) ProtoMessage() {}

func (x *AntiEntropySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropySummaryResponse.ProtoReflect.Descriptor instead.
func (*AntiEntropySummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{13}
}

func (x *AntiEntropySummaryResponse) GetResponderNodeId() string {
	if x != nil {
		return x.ResponderNodeId
	}
	return ""
}

func (x *AntiEntropySummaryResponse) GetConfigurationDigest() []byte {
	if x != nil {
		return x.ConfigurationDigest
	}
	return nil
}

func (x *AntiEntropySummaryResponse) GetRootDigest() []byte {
	if x != nil {
		return x.RootDigest
	}
	return nil
}

func (x *AntiEntropySummaryResponse) GetBucketDigests() [][]byte {
	if x != nil {
		return x.BucketDigests
	}
	return nil
}

// Requests records in one differing shared-data bucket.
type AntiEntropyBucketRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequesterNodeId     string                 `protobuf:"bytes,1,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	ReplicationFactor   int32                  `protobuf:"varint,2,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	ConfigurationDigest []byte                 `protobuf:"bytes,3,opt,name=configuration_digest,json=configurationDigest,proto3" json:"configuration_digest,omitempty"`
	Bucket              int32                  `protobuf:"varint,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AntiEntropyBucketRequest) Reset() {
	*x = AntiEntropyBucketRequest{}
	mi := &file_proto_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropyBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropyBucketRequest) ProtoMessage() {}

func (x *AntiEntropyBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropyBucketRequest.ProtoReflect.Descriptor instead.
func (*AntiEntropyBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{14}
}

func (x *AntiEntropyBucketRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

func (x *AntiEntropyBucketRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *AntiEntropyBucketRequest) GetConfigurationDigest() []byte {
	if x != nil {
		return x.ConfigurationDigest
	}
	return nil
}

func (x *AntiEntropyBucketRequest) GetBucket() int32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

type AntiEntropyKeyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Records       []*VersionedRecord     `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiEntropyKeyState) Reset() {
	*x = AntiEntropyKeyState{}
	mi := &file_proto_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropyKeyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropyKeyState) ProtoMessage() {}

func (x *AntiEntropyKeyState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropyKeyState.ProtoReflect.Descriptor instead.
func (*AntiEntropyKeyState) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{15}
}

func (x *AntiEntropyKeyState) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *AntiEntropyKeyState) GetRecords() []*VersionedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type AntiEntropyBucketResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResponderNodeId     string                 `protobuf:"bytes,1,opt,name=responder_node_id,json=responderNodeId,proto3" json:"responder_node_id,omitempty"`
	ConfigurationDigest []byte                 `protobuf:"bytes,2,opt,name=configuration_digest,json=configurationDigest,proto3" json:"configuration_digest,omitempty"`
	Bucket              int32                  `protobuf:"varint,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Keys                []*AntiEntropyKeyState `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AntiEntropyBucketResponse) Reset() {
	*x = AntiEntropyBucketResponse{}
	mi := &file_proto_kv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropyBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropyBucketResponse) ProtoMessage() {}

func (x *AntiEntropyBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropyBucketResponse.ProtoReflect.Descriptor instead.
func (*AntiEntropyBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{16}
}

func (x *AntiEntropyBucketResponse) GetResponderNodeId() string {
	if x != nil {
		return x.ResponderNodeId
	}
	return ""
}

func (x *AntiEntropyBucketResponse) GetConfigurationDigest() []byte {
	if x != nil {
		return x.ConfigurationDigest
	}
	return nil
}

func (x *AntiEntropyBucketResponse) GetBucket() int32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *AntiEntropyBucketResponse) GetKeys() []*AntiEntropyKeyState {
	if x != nil {
		return x.Keys
	}
	return nil
}

type MembershipStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipStatusRequest) Reset() {
	*x = MembershipStatusRequest{}
	mi := &file_proto_kv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatusRequest) ProtoMessage() {}

func (x *MembershipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatusRequest.ProtoReflect.Descriptor instead.
func (*MembershipStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{17}
}

type MembershipStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActiveEpoch     uint64                 `protobuf:"varint,2,opt,name=active_epoch,json=activeEpoch,proto3" json:"active_epoch,omitempty"`
	ActiveDigest    []byte                 `protobuf:"bytes,3,opt,name=active_digest,json=activeDigest,proto3" json:"active_digest,omitempty"`
	WritesPaused    bool                   `protobuf:"varint,4,opt,name=writes_paused,json=writesPaused,proto3" json:"writes_paused,omitempty"`
	PendingEpoch    uint64                 `protobuf:"varint,5,opt,name=pending_epoch,json=pendingEpoch,proto3" json:"pending_epoch,omitempty"`
	PendingDigest   []byte                 `protobuf:"bytes,6,opt,name=pending_digest,json=pendingDigest,proto3" json:"pending_digest,omitempty"`
	JoinCommitted   bool                   `protobuf:"varint,7,opt,name=join_committed,json=joinCommitted,proto3" json:"join_committed,omitempty"`
	ReplicasReady   bool                   `protobuf:"varint,8,opt,name=replicas_ready,json=replicasReady,proto3" json:"replicas_ready,omitempty"`
	ClientsReleased bool                   `protobuf:"varint,9,opt,name=clients_released,json=clientsReleased,proto3" json:"clients_released,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MembershipStatusResponse) Reset() {
	*x = MembershipStatusResponse{}
	mi := &file_proto_kv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatusResponse) ProtoMessage() {}

func (x *MembershipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatusResponse.ProtoReflect.Descriptor instead.
func (*MembershipStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{18}
}

func (x *MembershipStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MembershipStatusResponse) GetActiveEpoch() uint64 {
	if x != nil {
		return x.ActiveEpoch
	}
	return 0
}

func (x *MembershipStatusResponse) GetActiveDigest() []byte {
	if x != nil {
		return x.ActiveDigest
	}
	return nil
}

func (x *MembershipStatusResponse) GetWritesPaused() bool {
	if x != nil {
		return x.WritesPaused
	}
	return false
}

func (x *MembershipStatusResponse) GetPendingEpoch() uint64 {
	if x != nil {
		return x.PendingEpoch
	}
	return 0
}

func (x *MembershipStatusResponse) GetPendingDigest() []byte {
	if x != nil {
		return x.PendingDigest
	}
	return nil
}

func (x *MembershipStatusResponse) GetJoinCommitted() bool {
	if x != nil {
		return x.JoinCommitted
	}
	return false
}

func (x *MembershipStatusResponse) GetReplicasReady() bool {
	if x != nil {
		return x.ReplicasReady
	}
	return false
}

func (x *MembershipStatusResponse) GetClientsReleased() bool {
	if x != nil {
		return x.ClientsReleased
	}
	return false
}

type PrepareJoinPauseRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveEpoch        uint64                 `protobuf:"varint,1,opt,name=active_epoch,json=activeEpoch,proto3" json:"active_epoch,omitempty"`
	ActiveDigest       []byte                 `protobuf:"bytes,2,opt,name=active_digest,json=activeDigest,proto3" json:"active_digest,omitempty"`
	CandidateEpoch     uint64                 `protobuf:"varint,3,opt,name=candidate_epoch,json=candidateEpoch,proto3" json:"candidate_epoch,omitempty"`
	CandidateDigest    []byte                 `protobuf:"bytes,4,opt,name=candidate_digest,json=candidateDigest,proto3" json:"candidate_digest,omitempty"`
	JoiningNodeId      string                 `protobuf:"bytes,5,opt,name=joining_node_id,json=joiningNodeId,proto3" json:"joining_node_id,omitempty"`
	JoiningNodeAddress string                 `protobuf:"bytes,6,opt,name=joining_node_address,json=joiningNodeAddress,proto3" json:"joining_node_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrepareJoinPauseRequest) Reset() {
	*x = PrepareJoinPauseRequest{}
	mi := &file_proto_kv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareJoinPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareJoinPauseRequest) ProtoMessage() {}

func (x *PrepareJoinPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareJoinPauseRequest.ProtoReflect.Descriptor instead.
func (*PrepareJoinPauseRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{19}
}

func (x *PrepareJoinPauseRequest) GetActiveEpoch() uint64 {
	if x != nil {
		return x.ActiveEpoch
	}
	return 0
}

func (x *PrepareJoinPauseRequest) GetActiveDigest() []byte {
	if x != nil {
		return x.ActiveDigest
	}
	return nil
}

func (x *PrepareJoinPauseRequest) GetCandidateEpoch() uint64 {
	if x != nil {
		return x.CandidateEpoch
	}
	return 0
}

func (x *PrepareJoinPauseRequest) GetCandidateDigest() []byte {
	if x != nil {
		return x.CandidateDigest
	}
	return nil
}

func (x *PrepareJoinPauseRequest) GetJoiningNodeId() string {
	if x != nil {
		return x.JoiningNodeId
	}
	return ""
}

func (x *PrepareJoinPauseRequest) GetJoiningNodeAddress() string {
	if x != nil {
		return x.JoiningNodeAddress
	}
	return ""
}

type JoinDecisionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorNodeId string                 `protobuf:"bytes,1,opt,name=coordinator_node_id,json=coordinatorNodeId,proto3" json:"coordinator_node_id,omitempty"`
	ActiveEpoch       uint64                 `protobuf:"varint,2,opt,name=active_epoch,json=activeEpoch,proto3" json:"active_epoch,omitempty"`
	ActiveDigest      []byte                 `protobuf:"bytes,3,opt,name=active_digest,json=activeDigest,proto3" json:"active_digest,omitempty"`
	CandidateEpoch    uint64                 `protobuf:"varint,4,opt,name=candidate_epoch,json=candidateEpoch,proto3" json:"candidate_epoch,omitempty"`
	CandidateDigest   []byte                 `protobuf:"bytes,5,opt,name=candidate_digest,json=candidateDigest,proto3" json:"candidate_digest,omitempty"`
	Decision          JoinDecision           `protobuf:"varint,6,opt,name=decision,proto3,enum=kv.JoinDecision" json:"decision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JoinDecisionResponse) Reset() {
	*x = JoinDecisionResponse{}
	mi := &file_proto_kv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinDecisionResponse) ProtoMessage() {}

func (x *JoinDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinDecisionResponse.ProtoReflect.Descriptor instead.
func (*JoinDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{20}
}

func (x *JoinDecisionResponse) GetCoordinatorNodeId() string {
	if x != nil {
		return x.CoordinatorNodeId
	}
	return ""
}

func (x *JoinDecisionResponse) GetActiveEpoch() uint64 {
	if x != nil {
		return x.ActiveEpoch
	}
	return 0
}

func (x *JoinDecisionResponse) GetActiveDigest() []byte {
	if x != nil {
		return x.ActiveDigest
	}
	return nil
}

func (x *JoinDecisionResponse) GetCandidateEpoch() uint64 {
	if x != nil {
		return x.CandidateEpoch
	}
	return 0
}

func (x *JoinDecisionResponse) GetCandidateDigest() []byte {
	if x != nil {
		return x.CandidateDigest
	}
	return nil
}

func (x *JoinDecisionResponse) GetDecision() JoinDecision {
	if x != nil {
		return x.Decision
	}
	return JoinDecision_JOIN_DECISION_UNDECIDED
}

type PromotionStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CandidateEpoch    uint64                 `protobuf:"varint,2,opt,name=candidate_epoch,json=candidateEpoch,proto3" json:"candidate_epoch,omitempty"`
	CandidateDigest   []byte                 `protobuf:"bytes,3,opt,name=candidate_digest,json=candidateDigest,proto3" json:"candidate_digest,omitempty"`
	PromotionRecorded bool                   `protobuf:"varint,4,opt,name=promotion_recorded,json=promotionRecorded,proto3" json:"promotion_recorded,omitempty"`
	RequestsPaused    bool                   `protobuf:"varint,5,opt,name=requests_paused,json=requestsPaused,proto3" json:"requests_paused,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromotionStatusResponse) Reset() {
	*x = PromotionStatusResponse{}
	mi := &file_proto_kv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionStatusResponse) ProtoMessage() {}

func (x *PromotionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionStatusResponse.ProtoReflect.Descriptor instead.
func (*PromotionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{21}
}

func (x *PromotionStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PromotionStatusResponse) GetCandidateEpoch() uint64 {
	if x != nil {
		return x.CandidateEpoch
	}
	return 0
}

func (x *PromotionStatusResponse) GetCandidateDigest() []byte {
	if x != nil {
		return x.CandidateDigest
	}
	return nil
}

func (x *PromotionStatusResponse) GetPromotionRecorded() bool {
	if x != nil {
		return x.PromotionRecorded
	}
	return false
}

func (x *PromotionStatusResponse) GetRequestsPaused() bool {
	if x != nil {
		return x.RequestsPaused
	}
	return false
}

type JoinResumeDecisionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorNodeId     string                 `protobuf:"bytes,1,opt,name=coordinator_node_id,json=coordinatorNodeId,proto3" json:"coordinator_node_id,omitempty"`
	ActiveEpoch           uint64                 `protobuf:"varint,2,opt,name=active_epoch,json=activeEpoch,proto3" json:"active_epoch,omitempty"`
	ActiveDigest          []byte                 `protobuf:"bytes,3,opt,name=active_digest,json=activeDigest,proto3" json:"active_digest,omitempty"`
	CandidateEpoch        uint64                 `protobuf:"varint,4,opt,name=candidate_epoch,json=candidateEpoch,proto3" json:"candidate_epoch,omitempty"`
	CandidateDigest       []byte                 `protobuf:"bytes,5,opt,name=candidate_digest,json=candidateDigest,proto3" json:"candidate_digest,omitempty"`
	ResumeDecided         bool                   `protobuf:"varint,6,opt,name=resume_decided,json=resumeDecided,proto3" json:"resume_decided,omitempty"`
	ClientsReleaseDecided bool                   `protobuf:"varint,7,opt,name=clients_release_decided,json=clientsReleaseDecided,proto3" json:"clients_release_decided,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JoinResumeDecisionResponse) Reset() {
	*x = JoinResumeDecisionResponse{}
	mi := &file_proto_kv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResumeDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResumeDecisionResponse) ProtoMessage() {}

func (x *JoinResumeDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResumeDecisionResponse.ProtoReflect.Descriptor instead.
func (*JoinResumeDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{22}
}

func (x *JoinResumeDecisionResponse) GetCoordinatorNodeId() string {
	if x != nil {
		return x.CoordinatorNodeId
	}
	return ""
}

func (x *JoinResumeDecisionResponse) GetActiveEpoch() uint64 {
	if x != nil {
		return x.ActiveEpoch
	}
	return 0
}

func (x *JoinResumeDecisionResponse) GetActiveDigest() []byte {
	if x != nil {
		return x.ActiveDigest
	}
	return nil
}

func (x *JoinResumeDecisionResponse) GetCandidateEpoch() uint64 {
	if x != nil {
		return x.CandidateEpoch
	}
	return 0
}

func (x *JoinResumeDecisionResponse) GetCandidateDigest() []byte {
	if x != nil {
		return x.CandidateDigest
	}
	return nil
}

func (x *JoinResumeDecisionResponse) GetResumeDecided() bool {
	if x != nil {
		return x.ResumeDecided
	}
	return false
}

func (x *JoinResumeDecisionResponse) GetClientsReleaseDecided() bool {
	if x != nil {
		return x.ClientsReleaseDecided
	}
	return false
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x02kv\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\r\n" +
	"\vPutResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\"\xfa\x01\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12/\n" +
	"\bversions\x18\x03 \x03(\v2\x13.kv.VersionedRecordR\bversions\x126\n" +
	"\acontext\x18\x04 \x03(\v2\x1c.kv.GetResponse.ContextEntryR\acontext\x12\x1a\n" +
	"\bconflict\x18\x05 \x01(\bR\bconflict\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\xb1\x01\n" +
	"\x0fVersionedRecord\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x124\n" +
	"\x05clock\x18\x02 \x03(\v2\x1e.kv.VersionedRecord.ClockEntryR\x05clock\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x1a8\n" +
	"\n" +
	"ClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"U\n" +
	"\x14ReplicaRecordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x06record\x18\x02 \x01(\v2\x13.kv.VersionedRecordR\x06record\"\x17\n" +
	"\x15ReplicaRecordResponse\"\x8f\x01\n" +
	"\x19ReplicaRecordReadResponse\x12+\n" +
	"\x06record\x18\x01 \x01(\v2\x13.kv.VersionedRecordR\x06record\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12-\n" +
	"\arecords\x18\x03 \x03(\v2\x13.kv.VersionedRecordR\arecords\"\xc9\x01\n" +
	"\x0eResolveRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x129\n" +
	"\acontext\x18\x03 \x03(\v2\x1f.kv.ResolveRequest.ContextEntryR\acontext\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x11\n" +
	"\x0fResolveResponse\"\xa9\x01\n" +
	"\x19AntiEntropySummaryRequest\x12*\n" +
	"\x11requester_node_id\x18\x01 \x01(\tR\x0frequesterNodeId\x12-\n" +
	"\x12replication_factor\x18\x02 \x01(\x05R\x11replicationFactor\x121\n" +
	"\x14configuration_digest\x18\x03 \x01(\fR\x13configurationDigest\"\xc3\x01\n" +
	"\x1aAntiEntropySummaryResponse\x12*\n" +
	"\x11responder_node_id\x18\x01 \x01(\tR\x0fresponderNodeId\x121\n" +
	"\x14configuration_digest\x18\x02 \x01(\fR\x13configurationDigest\x12\x1f\n" +
	"\vroot_digest\x18\x03 \x01(\fR\n" +
	"rootDigest\x12%\n" +
	"\x0ebucket_digests\x18\x04 \x03(\fR\rbucketDigests\"\xc0\x01\n" +
	"\x18AntiEntropyBucketRequest\x12*\n" +
	"\x11requester_node_id\x18\x01 \x01(\tR\x0frequesterNodeId\x12-\n" +
	"\x12replication_factor\x18\x02 \x01(\x05R\x11replicationFactor\x121\n" +
	"\x14configuration_digest\x18\x03 \x01(\fR\x13configurationDigest\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\x05R\x06bucket\"V\n" +
	"\x13AntiEntropyKeyState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12-\n" +
	"\arecords\x18\x02 \x03(\v2\x13.kv.VersionedRecordR\arecords\"\xbf\x01\n" +
	"\x19AntiEntropyBucketResponse\x12*\n" +
	"\x11responder_node_id\x18\x01 \x01(\tR\x0fresponderNodeId\x121\n" +
	"\x14configuration_digest\x18\x02 \x01(\fR\x13configurationDigest\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\x05R\x06bucket\x12+\n" +
	"\x04keys\x18\x04 \x03(\v2\x17.kv.AntiEntropyKeyStateR\x04keys\"\x19\n" +
	"\x17MembershipStatusRequest\"\xe5\x02\n" +
	"\x18MembershipStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\factive_epoch\x18\x02 \x01(\x04R\vactiveEpoch\x12#\n" +
	"\ractive_digest\x18\x03 \x01(\fR\factiveDigest\x12#\n" +
	"\rwrites_paused\x18\x04 \x01(\bR\fwritesPaused\x12#\n" +
	"\rpending_epoch\x18\x05 \x01(\x04R\fpendingEpoch\x12%\n" +
	"\x0epending_digest\x18\x06 \x01(\fR\rpendingDigest\x12%\n" +
	"\x0ejoin_committed\x18\a \x01(\bR\rjoinCommitted\x12%\n" +
	"\x0ereplicas_ready\x18\b \x01(\bR\rreplicasReady\x12)\n" +
	"\x10clients_released\x18\t \x01(\bR\x0fclientsReleased\"\x8f\x02\n" +
	"\x17PrepareJoinPauseRequest\x12!\n" +
	"\factive_epoch\x18\x01 \x01(\x04R\vactiveEpoch\x12#\n" +
	"\ractive_digest\x18\x02 \x01(\fR\factiveDigest\x12'\n" +
	"\x0fcandidate_epoch\x18\x03 \x01(\x04R\x0ecandidateEpoch\x12)\n" +
	"\x10candidate_digest\x18\x04 \x01(\fR\x0fcandidateDigest\x12&\n" +
	"\x0fjoining_node_id\x18\x05 \x01(\tR\rjoiningNodeId\x120\n" +
	"\x14joining_node_address\x18\x06 \x01(\tR\x12joiningNodeAddress\"\x90\x02\n" +
	"\x14JoinDecisionResponse\x12.\n" +
	"\x13coordinator_node_id\x18\x01 \x01(\tR\x11coordinatorNodeId\x12!\n" +
	"\factive_epoch\x18\x02 \x01(\x04R\vactiveEpoch\x12#\n" +
	"\ractive_digest\x18\x03 \x01(\fR\factiveDigest\x12'\n" +
	"\x0fcandidate_epoch\x18\x04 \x01(\x04R\x0ecandidateEpoch\x12)\n" +
	"\x10candidate_digest\x18\x05 \x01(\fR\x0fcandidateDigest\x12,\n" +
	"\bdecision\x18\x06 \x01(\x0e2\x10.kv.JoinDecisionR\bdecision\"\xde\x01\n" +
	"\x17PromotionStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fcandidate_epoch\x18\x02 \x01(\x04R\x0ecandidateEpoch\x12)\n" +
	"\x10candidate_digest\x18\x03 \x01(\fR\x0fcandidateDigest\x12-\n" +
	"\x12promotion_recorded\x18\x04 \x01(\bR\x11promotionRecorded\x12'\n" +
	"\x0frequests_paused\x18\x05 \x01(\bR\x0erequestsPaused\"\xc7\x02\n" +
	"\x1aJoinResumeDecisionResponse\x12.\n" +
	"\x13coordinator_node_id\x18\x01 \x01(\tR\x11coordinatorNodeId\x12!\n" +
	"\factive_epoch\x18\x02 \x01(\x04R\vactiveEpoch\x12#\n" +
	"\ractive_digest\x18\x03 \x01(\fR\factiveDigest\x12'\n" +
	"\x0fcandidate_epoch\x18\x04 \x01(\x04R\x0ecandidateEpoch\x12)\n" +
	"\x10candidate_digest\x18\x05 \x01(\fR\x0fcandidateDigest\x12%\n" +
	"\x0eresume_decided\x18\x06 \x01(\bR\rresumeDecided\x126\n" +
	"\x17clients_release_decided\x18\a \x01(\bR\x15clientsReleaseDecided*^\n" +
	"\fJoinDecision\x12\x1b\n" +
	"\x17JOIN_DECISION_UNDECIDED\x10\x00\x12\x18\n" +
	"\x14JOIN_DECISION_COMMIT\x10\x01\x12\x17\n" +
	"\x13JOIN_DECISION_ABORT\x10\x022\x89\f\n" +
	"\rKeyValueStore\x12&\n" +
	"\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12&\n" +
	"\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\x12/\n" +
	"\x06Delete\x12\x11.kv.DeleteRequest\x1a\x12.kv.DeleteResponse\x12I\n" +
	"\x12ApplyReplicaRecord\x12\x18.kv.ReplicaRecordRequest\x1a\x19.kv.ReplicaRecordResponse\x12B\n" +
	"\x11ReadReplicaRecord\x12\x0e.kv.GetRequest\x1a\x1d.kv.ReplicaRecordReadResponse\x122\n" +
	"\aResolve\x12\x12.kv.ResolveRequest\x1a\x13.kv.ResolveResponse\x12S\n" +
	"\x12AntiEntropySummary\x12\x1d.kv.AntiEntropySummaryRequest\x1a\x1e.kv.AntiEntropySummaryResponse\x12P\n" +
	"\x11AntiEntropyBucket\x12\x1c.kv.AntiEntropyBucketRequest\x1a\x1d.kv.AntiEntropyBucketResponse\x12P\n" +
	"\x13GetMembershipStatus\x12\x1b.kv.MembershipStatusRequest\x1a\x1c.kv.MembershipStatusResponse\x12M\n" +
	"\x10PrepareJoinPause\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12K\n" +
	"\x0eAbortJoinPause\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12L\n" +
	"\x0fCommitJoinPause\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12H\n" +
	"\x0fGetJoinDecision\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x18.kv.JoinDecisionResponse\x12I\n" +
	"\fActivateJoin\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12G\n" +
	"\vPromoteJoin\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1b.kv.PromotionStatusResponse\x12T\n" +
	"\x15GetJoinResumeDecision\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1e.kv.JoinResumeDecisionResponse\x12O\n" +
	"\x12EnableJoinReplicas\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12O\n" +
	"\x12ReleaseJoinClients\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12Q\n" +
	"\x14CoordinateJoinCommit\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12U\n" +
	"\x18CoordinateJoinActivation\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponse\x12Q\n" +
	"\x14CoordinateJoinResume\x12\x1b.kv.PrepareJoinPauseRequest\x1a\x1c.kv.MembershipStatusResponseB7Z5github.com/A-s-n55555/distributed-kv-store/proto;kvpbb\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_kv_proto_goTypes = []any{
	(JoinDecision)(0),                  // 0: kv.JoinDecision
	(*PutRequest)(nil),                 // 1: kv.PutRequest
	(*PutResponse)(nil),                // 2: kv.PutResponse
	(*GetRequest)(nil),                 // 3: kv.GetRequest
	(*GetResponse)(nil),                // 4: kv.GetResponse
	(*DeleteRequest)(nil),              // 5: kv.DeleteRequest
	(*DeleteResponse)(nil),             // 6: kv.DeleteResponse
	(*VersionedRecord)(nil),            // 7: kv.VersionedRecord
	(*ReplicaRecordRequest)(nil),       // 8: kv.ReplicaRecordRequest
	(*ReplicaRecordResponse)(nil),      // 9: kv.ReplicaRecordResponse
	(*ReplicaRecordReadResponse)(nil),  // 10: kv.ReplicaRecordReadResponse
	(*ResolveRequest)(nil),             // 11: kv.ResolveRequest
	(*ResolveResponse)(nil),            // 12: kv.ResolveResponse
	(*AntiEntropySummaryRequest)(nil),  // 13: kv.AntiEntropySummaryRequest
	(*AntiEntropySummaryResponse)(nil), // 14: kv.AntiEntropySummaryResponse
	(*AntiEntropyBucketRequest)(nil),   // 15: kv.AntiEntropyBucketRequest
	(*AntiEntropyKeyState)(nil),        // 16: kv.AntiEntropyKeyState
	(*AntiEntropyBucketResponse)(nil),  // 17: kv.AntiEntropyBucketResponse
	(*MembershipStatusRequest)(nil),    // 18: kv.MembershipStatusRequest
	(*MembershipStatusResponse)(nil),   // 19: kv.MembershipStatusResponse
	(*PrepareJoinPauseRequest)(nil),    // 20: kv.PrepareJoinPauseRequest
	(*JoinDecisionResponse)(nil),       // 21: kv.JoinDecisionResponse
	(*PromotionStatusResponse)(nil),    // 22: kv.PromotionStatusResponse
	(*JoinResumeDecisionResponse)(nil), // 23: kv.JoinResumeDecisionResponse
	nil,                                // 24: kv.GetResponse.ContextEntry
	nil,                                // 25: kv.VersionedRecord.ClockEntry
	nil,                                // 26: kv.ResolveRequest.ContextEntry
}
var file_proto_kv_proto_depIdxs = []int32{
	7,  // 0: kv.GetResponse.versions:type_name -> kv.VersionedRecord
	24, // 1: kv.GetResponse.context:type_name -> kv.GetResponse.ContextEntry
	25, // 2: kv.VersionedRecord.clock:type_name -> kv.VersionedRecord.ClockEntry
	7,  // 3: kv.ReplicaRecordRequest.record:type_name -> kv.VersionedRecord
	7,  // 4: kv.ReplicaRecordReadResponse.record:type_name -> kv.VersionedRecord
	7,  // 5: kv.ReplicaRecordReadResponse.records:type_name -> kv.VersionedRecord
	26, // 6: kv.ResolveRequest.context:type_name -> kv.ResolveRequest.ContextEntry
	7,  // 7: kv.AntiEntropyKeyState.records:type_name -> kv.VersionedRecord
	16, // 8: kv.AntiEntropyBucketResponse.keys:type_name -> kv.AntiEntropyKeyState
	0,  // 9: kv.JoinDecisionResponse.decision:type_name -> kv.JoinDecision
	1,  // 10: kv.KeyValueStore.Put:input_type -> kv.PutRequest
	3,  // 11: kv.KeyValueStore.Get:input_type -> kv.GetRequest
	5,  // 12: kv.KeyValueStore.Delete:input_type -> kv.DeleteRequest
	8,  // 13: kv.KeyValueStore.ApplyReplicaRecord:input_type -> kv.ReplicaRecordRequest
	3,  // 14: kv.KeyValueStore.ReadReplicaRecord:input_type -> kv.GetRequest
	11, // 15: kv.KeyValueStore.Resolve:input_type -> kv.ResolveRequest
	13, // 16: kv.KeyValueStore.AntiEntropySummary:input_type -> kv.AntiEntropySummaryRequest
	15, // 17: kv.KeyValueStore.AntiEntropyBucket:input_type -> kv.AntiEntropyBucketRequest
	18, // 18: kv.KeyValueStore.GetMembershipStatus:input_type -> kv.MembershipStatusRequest
	20, // 19: kv.KeyValueStore.PrepareJoinPause:input_type -> kv.PrepareJoinPauseRequest
	20, // 20: kv.KeyValueStore.AbortJoinPause:input_type -> kv.PrepareJoinPauseRequest
	20, // 21: kv.KeyValueStore.CommitJoinPause:input_type -> kv.PrepareJoinPauseRequest
	20, // 22: kv.KeyValueStore.GetJoinDecision:input_type -> kv.PrepareJoinPauseRequest
	20, // 23: kv.KeyValueStore.ActivateJoin:input_type -> kv.PrepareJoinPauseRequest
	20, // 24: kv.KeyValueStore.PromoteJoin:input_type -> kv.PrepareJoinPauseRequest
	20, // 25: kv.KeyValueStore.GetJoinResumeDecision:input_type -> kv.PrepareJoinPauseRequest
	20, // 26: kv.KeyValueStore.EnableJoinReplicas:input_type -> kv.PrepareJoinPauseRequest
	20, // 27: kv.KeyValueStore.ReleaseJoinClients:input_type -> kv.PrepareJoinPauseRequest
	20, // 28: kv.KeyValueStore.CoordinateJoinCommit:input_type -> kv.PrepareJoinPauseRequest
	20, // 29: kv.KeyValueStore.CoordinateJoinActivation:input_type -> kv.PrepareJoinPauseRequest
	20, // 30: kv.KeyValueStore.CoordinateJoinResume:input_type -> kv.PrepareJoinPauseRequest
	2,  // 31: kv.KeyValueStore.Put:output_type -> kv.PutResponse
	4,  // 32: kv.KeyValueStore.Get:output_type -> kv.GetResponse
	6,  // 33: kv.KeyValueStore.Delete:output_type -> kv.DeleteResponse
	9,  // 34: kv.KeyValueStore.ApplyReplicaRecord:output_type -> kv.ReplicaRecordResponse
	10, // 35: kv.KeyValueStore.ReadReplicaRecord:output_type -> kv.ReplicaRecordReadResponse
	12, // 36: kv.KeyValueStore.Resolve:output_type -> kv.ResolveResponse
	14, // 37: kv.KeyValueStore.AntiEntropySummary:output_type -> kv.AntiEntropySummaryResponse
	17, // 38: kv.KeyValueStore.AntiEntropyBucket:output_type -> kv.AntiEntropyBucketResponse
	19, // 39: kv.KeyValueStore.GetMembershipStatus:output_type -> kv.MembershipStatusResponse
	19, // 40: kv.KeyValueStore.PrepareJoinPause:output_type -> kv.MembershipStatusResponse
	19, // 41: kv.KeyValueStore.AbortJoinPause:output_type -> kv.MembershipStatusResponse
	19, // 42: kv.KeyValueStore.CommitJoinPause:output_type -> kv.MembershipStatusResponse
	21, // 43: kv.KeyValueStore.GetJoinDecision:output_type -> kv.JoinDecisionResponse
	19, // 44: kv.KeyValueStore.ActivateJoin:output_type -> kv.MembershipStatusResponse
	22, // 45: kv.KeyValueStore.PromoteJoin:output_type -> kv.PromotionStatusResponse
	23, // 46: kv.KeyValueStore.GetJoinResumeDecision:output_type -> kv.JoinResumeDecisionResponse
	19, // 47: kv.KeyValueStore.EnableJoinReplicas:output_type -> kv.MembershipStatusResponse
	19, // 48: kv.KeyValueStore.ReleaseJoinClients:output_type -> kv.MembershipStatusResponse
	19, // 49: kv.KeyValueStore.CoordinateJoinCommit:output_type -> kv.MembershipStatusResponse
	19, // 50: kv.KeyValueStore.CoordinateJoinActivation:output_type -> kv.MembershipStatusResponse
	19, // 51: kv.KeyValueStore.CoordinateJoinResume:output_type -> kv.MembershipStatusResponse
	31, // [31:52] is the sub-list for method output_type
	10, // [10:31] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		EnumInfos:         file_proto_kv_proto_enumTypes,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
