// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/kv.proto

package kvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyValueStore_Put_FullMethodName                      = "/kv.KeyValueStore/Put"
	KeyValueStore_Get_FullMethodName                      = "/kv.KeyValueStore/Get"
	KeyValueStore_Delete_FullMethodName                   = "/kv.KeyValueStore/Delete"
	KeyValueStore_ApplyReplicaRecord_FullMethodName       = "/kv.KeyValueStore/ApplyReplicaRecord"
	KeyValueStore_ReadReplicaRecord_FullMethodName        = "/kv.KeyValueStore/ReadReplicaRecord"
	KeyValueStore_Resolve_FullMethodName                  = "/kv.KeyValueStore/Resolve"
	KeyValueStore_AntiEntropySummary_FullMethodName       = "/kv.KeyValueStore/AntiEntropySummary"
	KeyValueStore_AntiEntropyBucket_FullMethodName        = "/kv.KeyValueStore/AntiEntropyBucket"
	KeyValueStore_GetMembershipStatus_FullMethodName      = "/kv.KeyValueStore/GetMembershipStatus"
	KeyValueStore_PrepareJoinPause_FullMethodName         = "/kv.KeyValueStore/PrepareJoinPause"
	KeyValueStore_AbortJoinPause_FullMethodName           = "/kv.KeyValueStore/AbortJoinPause"
	KeyValueStore_CommitJoinPause_FullMethodName          = "/kv.KeyValueStore/CommitJoinPause"
	KeyValueStore_GetJoinDecision_FullMethodName          = "/kv.KeyValueStore/GetJoinDecision"
	KeyValueStore_ActivateJoin_FullMethodName             = "/kv.KeyValueStore/ActivateJoin"
	KeyValueStore_PromoteJoin_FullMethodName              = "/kv.KeyValueStore/PromoteJoin"
	KeyValueStore_GetJoinResumeDecision_FullMethodName    = "/kv.KeyValueStore/GetJoinResumeDecision"
	KeyValueStore_EnableJoinReplicas_FullMethodName       = "/kv.KeyValueStore/EnableJoinReplicas"
	KeyValueStore_ReleaseJoinClients_FullMethodName       = "/kv.KeyValueStore/ReleaseJoinClients"
	KeyValueStore_CoordinateJoinCommit_FullMethodName     = "/kv.KeyValueStore/CoordinateJoinCommit"
	KeyValueStore_CoordinateJoinActivation_FullMethodName = "/kv.KeyValueStore/CoordinateJoinActivation"
	KeyValueStore_CoordinateJoinResume_FullMethodName     = "/kv.KeyValueStore/CoordinateJoinResume"
)

// KeyValueStoreClient is the client API for KeyValueStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValueStoreClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ApplyReplicaRecord(ctx context.Context, in *ReplicaRecordRequest, opts ...grpc.CallOption) (*ReplicaRecordResponse, error)
	ReadReplicaRecord(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ReplicaRecordReadResponse, error)
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	AntiEntropySummary(ctx context.Context, in *AntiEntropySummaryRequest, opts ...grpc.CallOption) (*AntiEntropySummaryResponse, error)
	AntiEntropyBucket(ctx context.Context, in *AntiEntropyBucketRequest, opts ...grpc.CallOption) (*AntiEntropyBucketResponse, error)
	GetMembershipStatus(ctx context.Context, in *MembershipStatusRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	PrepareJoinPause(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	AbortJoinPause(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	CommitJoinPause(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	GetJoinDecision(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*JoinDecisionResponse, error)
	ActivateJoin(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	PromoteJoin(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*PromotionStatusResponse, error)
	GetJoinResumeDecision(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*JoinResumeDecisionResponse, error)
	EnableJoinReplicas(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	ReleaseJoinClients(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	CoordinateJoinCommit(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	CoordinateJoinActivation(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
	CoordinateJoinResume(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error)
}

type keyValueStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueStoreClient(cc grpc.ClientConnInterface) KeyValueStoreClient {
	return &keyValueStoreClient{cc}
}

func (c *keyValueStoreClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) ApplyReplicaRecord(ctx context.Context, in *ReplicaRecordRequest, opts ...grpc.CallOption) (*ReplicaRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaRecordResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_ApplyReplicaRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) ReadReplicaRecord(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ReplicaRecordReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaRecordReadResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_ReadReplicaRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) AntiEntropySummary(ctx context.Context, in *AntiEntropySummaryRequest, opts ...grpc.CallOption) (*AntiEntropySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AntiEntropySummaryResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_AntiEntropySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) AntiEntropyBucket(ctx context.Context, in *AntiEntropyBucketRequest, opts ...grpc.CallOption) (*AntiEntropyBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AntiEntropyBucketResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_AntiEntropyBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) GetMembershipStatus(ctx context.Context, in *MembershipStatusRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_GetMembershipStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) PrepareJoinPause(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_PrepareJoinPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) AbortJoinPause(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_AbortJoinPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) CommitJoinPause(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_CommitJoinPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) GetJoinDecision(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*JoinDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinDecisionResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_GetJoinDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) ActivateJoin(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_ActivateJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) PromoteJoin(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*PromotionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromotionStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_PromoteJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) GetJoinResumeDecision(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*JoinResumeDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResumeDecisionResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_GetJoinResumeDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) EnableJoinReplicas(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_EnableJoinReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) ReleaseJoinClients(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_ReleaseJoinClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) CoordinateJoinCommit(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_CoordinateJoinCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) CoordinateJoinActivation(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_CoordinateJoinActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) CoordinateJoinResume(ctx context.Context, in *PrepareJoinPauseRequest, opts ...grpc.CallOption) (*MembershipStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipStatusResponse)
	err := c.cc.Invoke(ctx, KeyValueStore_CoordinateJoinResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueStoreServer is the server API for KeyValueStore service.
// All implementations must embed UnimplementedKeyValueStoreServer
// for forward compatibility.
type KeyValueStoreServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ApplyReplicaRecord(context.Context, *ReplicaRecordRequest) (*ReplicaRecordResponse, error)
	ReadReplicaRecord(context.Context, *GetRequest) (*ReplicaRecordReadResponse, error)
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	AntiEntropySummary(context.Context, *AntiEntropySummaryRequest) (*AntiEntropySummaryResponse, error)
	AntiEntropyBucket(context.Context, *AntiEntropyBucketRequest) (*AntiEntropyBucketResponse, error)
	GetMembershipStatus(context.Context, *MembershipStatusRequest) (*MembershipStatusResponse, error)
	PrepareJoinPause(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	AbortJoinPause(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	CommitJoinPause(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	GetJoinDecision(context.Context, *PrepareJoinPauseRequest) (*JoinDecisionResponse, error)
	ActivateJoin(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	PromoteJoin(context.Context, *PrepareJoinPauseRequest) (*PromotionStatusResponse, error)
	GetJoinResumeDecision(context.Context, *PrepareJoinPauseRequest) (*JoinResumeDecisionResponse, error)
	EnableJoinReplicas(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	ReleaseJoinClients(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	CoordinateJoinCommit(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	CoordinateJoinActivation(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	CoordinateJoinResume(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error)
	mustEmbedUnimplementedKeyValueStoreServer()
}

// UnimplementedKeyValueStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyValueStoreServer struct{}

func (UnimplementedKeyValueStoreServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKeyValueStoreServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKeyValueStoreServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKeyValueStoreServer) ApplyReplicaRecord(context.Context, *ReplicaRecordRequest) (*ReplicaRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyReplicaRecord not implemented")
}
func (UnimplementedKeyValueStoreServer) ReadReplicaRecord(context.Context, *GetRequest) (*ReplicaRecordReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadReplicaRecord not implemented")
}
func (UnimplementedKeyValueStoreServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedKeyValueStoreServer) AntiEntropySummary(context.Context, *AntiEntropySummaryRequest) (*AntiEntropySummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AntiEntropySummary not implemented")
}
func (UnimplementedKeyValueStoreServer) AntiEntropyBucket(context.Context, *AntiEntropyBucketRequest) (*AntiEntropyBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AntiEntropyBucket not implemented")
}
func (UnimplementedKeyValueStoreServer) GetMembershipStatus(context.Context, *MembershipStatusRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembershipStatus not implemented")
}
func (UnimplementedKeyValueStoreServer) PrepareJoinPause(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareJoinPause not implemented")
}
func (UnimplementedKeyValueStoreServer) AbortJoinPause(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortJoinPause not implemented")
}
func (UnimplementedKeyValueStoreServer) CommitJoinPause(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitJoinPause not implemented")
}
func (UnimplementedKeyValueStoreServer) GetJoinDecision(context.Context, *PrepareJoinPauseRequest) (*JoinDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJoinDecision not implemented")
}
func (UnimplementedKeyValueStoreServer) ActivateJoin(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateJoin not implemented")
}
func (UnimplementedKeyValueStoreServer) PromoteJoin(context.Context, *PrepareJoinPauseRequest) (*PromotionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteJoin not implemented")
}
func (UnimplementedKeyValueStoreServer) GetJoinResumeDecision(context.Context, *PrepareJoinPauseRequest) (*JoinResumeDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJoinResumeDecision not implemented")
}
func (UnimplementedKeyValueStoreServer) EnableJoinReplicas(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableJoinReplicas not implemented")
}
func (UnimplementedKeyValueStoreServer) ReleaseJoinClients(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseJoinClients not implemented")
}
func (UnimplementedKeyValueStoreServer) CoordinateJoinCommit(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoordinateJoinCommit not implemented")
}
func (UnimplementedKeyValueStoreServer) CoordinateJoinActivation(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoordinateJoinActivation not implemented")
}
func (UnimplementedKeyValueStoreServer) CoordinateJoinResume(context.Context, *PrepareJoinPauseRequest) (*MembershipStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoordinateJoinResume not implemented")
}
func (UnimplementedKeyValueStoreServer) mustEmbedUnimplementedKeyValueStoreServer() {}
func (UnimplementedKeyValueStoreServer) testEmbeddedByValue()                       {}

// UnsafeKeyValueStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValueStoreServer will
// result in compilation errors.
type UnsafeKeyValueStoreServer interface {
	mustEmbedUnimplementedKeyValueStoreServer()
}

func RegisterKeyValueStoreServer(s grpc.ServiceRegistrar, srv KeyValueStoreServer) {
	// If the following call panics, it indicates UnimplementedKeyValueStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyValueStore_ServiceDesc, srv)
}

func _KeyValueStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_ApplyReplicaRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).ApplyReplicaRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_ApplyReplicaRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).ApplyReplicaRecord(ctx, req.(*ReplicaRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_ReadReplicaRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).ReadReplicaRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_ReadReplicaRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).ReadReplicaRecord(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_AntiEntropySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntiEntropySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).AntiEntropySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_AntiEntropySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).AntiEntropySummary(ctx, req.(*AntiEntropySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_AntiEntropyBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntiEntropyBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).AntiEntropyBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_AntiEntropyBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).AntiEntropyBucket(ctx, req.(*AntiEntropyBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_GetMembershipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).GetMembershipStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_GetMembershipStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).GetMembershipStatus(ctx, req.(*MembershipStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_PrepareJoinPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).PrepareJoinPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_PrepareJoinPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).PrepareJoinPause(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_AbortJoinPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).AbortJoinPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_AbortJoinPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).AbortJoinPause(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_CommitJoinPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).CommitJoinPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_CommitJoinPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).CommitJoinPause(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_GetJoinDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).GetJoinDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_GetJoinDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).GetJoinDecision(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_ActivateJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).ActivateJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_ActivateJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).ActivateJoin(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_PromoteJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).PromoteJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_PromoteJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).PromoteJoin(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_GetJoinResumeDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).GetJoinResumeDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_GetJoinResumeDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).GetJoinResumeDecision(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_EnableJoinReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).EnableJoinReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_EnableJoinReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).EnableJoinReplicas(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_ReleaseJoinClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).ReleaseJoinClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_ReleaseJoinClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).ReleaseJoinClients(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_CoordinateJoinCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).CoordinateJoinCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_CoordinateJoinCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).CoordinateJoinCommit(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_CoordinateJoinActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).CoordinateJoinActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_CoordinateJoinActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).CoordinateJoinActivation(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_CoordinateJoinResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareJoinPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).CoordinateJoinResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStore_CoordinateJoinResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).CoordinateJoinResume(ctx, req.(*PrepareJoinPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyValueStore_ServiceDesc is the grpc.ServiceDesc for KeyValueStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValueStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv.KeyValueStore",
	HandlerType: (*KeyValueStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _KeyValueStore_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KeyValueStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KeyValueStore_Delete_Handler,
		},
		{
			MethodName: "ApplyReplicaRecord",
			Handler:    _KeyValueStore_ApplyReplicaRecord_Handler,
		},
		{
			MethodName: "ReadReplicaRecord",
			Handler:    _KeyValueStore_ReadReplicaRecord_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _KeyValueStore_Resolve_Handler,
		},
		{
			MethodName: "AntiEntropySummary",
			Handler:    _KeyValueStore_AntiEntropySummary_Handler,
		},
		{
			MethodName: "AntiEntropyBucket",
			Handler:    _KeyValueStore_AntiEntropyBucket_Handler,
		},
		{
			MethodName: "GetMembershipStatus",
			Handler:    _KeyValueStore_GetMembershipStatus_Handler,
		},
		{
			MethodName: "PrepareJoinPause",
			Handler:    _KeyValueStore_PrepareJoinPause_Handler,
		},
		{
			MethodName: "AbortJoinPause",
			Handler:    _KeyValueStore_AbortJoinPause_Handler,
		},
		{
			MethodName: "CommitJoinPause",
			Handler:    _KeyValueStore_CommitJoinPause_Handler,
		},
		{
			MethodName: "GetJoinDecision",
			Handler:    _KeyValueStore_GetJoinDecision_Handler,
		},
		{
			MethodName: "ActivateJoin",
			Handler:    _KeyValueStore_ActivateJoin_Handler,
		},
		{
			MethodName: "PromoteJoin",
			Handler:    _KeyValueStore_PromoteJoin_Handler,
		},
		{
			MethodName: "GetJoinResumeDecision",
			Handler:    _KeyValueStore_GetJoinResumeDecision_Handler,
		},
		{
			MethodName: "EnableJoinReplicas",
			Handler:    _KeyValueStore_EnableJoinReplicas_Handler,
		},
		{
			MethodName: "ReleaseJoinClients",
			Handler:    _KeyValueStore_ReleaseJoinClients_Handler,
		},
		{
			MethodName: "CoordinateJoinCommit",
			Handler:    _KeyValueStore_CoordinateJoinCommit_Handler,
		},
		{
			MethodName: "CoordinateJoinActivation",
			Handler:    _KeyValueStore_CoordinateJoinActivation_Handler,
		},
		{
			MethodName: "CoordinateJoinResume",
			Handler:    _KeyValueStore_CoordinateJoinResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kv.proto",
}
